version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: monomemo
      POSTGRES_USER: monomemo_user
      POSTGRES_PASSWORD: monomemo_pass
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
