[phases.setup]
nixPkgs = ['php82', 'nodejs_20', 'composer']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t public'